openapi: 3.0.0
info:
  title: Avaloq POC API
  version: 1.0.0
paths:
  /api/health:
    get:
      summary: This API is to check Application Health Status 
      responses:
        '200':
          description: Application is Up and Running
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string
        '404':
          description: Page not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/dirlist:
    post:
      summary: Executes the command from the config file
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Command executed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string
        '500':
          description: Error executing command
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/login:
    post:
      summary: Provide login credentials to get JWT
      requestBody:
        content:
          application/json:
            schema:
              type: object 
      responses:
        '200':
          description: Login Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Page not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/whoami:
    get:
      summary: Execute command from config file for current user 
      responses:
        '200':
          description: Command executed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string
        '500':
          description: Error executing command
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Page not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string    
