openapi: 3.0.0
info:
  title: Avaloq POC API
  version: 1.0.0
paths:
  /api/v1/execute:
    get:
      summary: Executes the command from the config file
      parameters:
        - name: name
          in: query
          description: Name of the user
          required: true
          schema:
            type: string
        - name: X-Auth-Token
          in: header
          description: Authorization token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Command executed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string
        '500':
          description: Error executing command
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/login:
    get:
      summary: Provide login credentials to get JWT 
      responses:
        '200':
          description: Login Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Page not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string    
